# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.4
pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip git git-core libc-client-dev libkrb5-dev && rm -r /var/lib/apt/lists/*
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
          - cp .env.example .env
          - php artisan key:generate
          - test -d security-checker || git clone https://github.com/sensiolabs/security-checker.git
          - cd security-checker
          - composer install
          - cd ..
          - vendor/bin/phpcs --standard=PSR2 --extensions=php app
    - step:
        caches:
          - composer
        script:
          - set +e
          - apt-get update && apt-get install -y unzip git git-core libc-client-dev libkrb5-dev && rm -r /var/lib/apt/lists/*
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
          - cp .env.example .env
          - php artisan key:generate
          - vendor/bin/phpunit

          